# Generated by Django 6.0.6 on 2026-06-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id_veterinario', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('anios_experiencia', models.IntegerField(blank=True, null=True)),
                ('universidad', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_registro', models.CharField(max_length=50, unique=True)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'veterinario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VeterinarioEspecialidad',
            fields=[
                ('id_veterinario_especialidad', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'veterinario_especialidad',
                'managed': False,
            },
        ),
    ]
